#!/usr/bin/env python3
"""
Generates vanilla.yml from the game's WeatherSelectionPrototypes.cfg.

Only the regions in REGIONS are included, in that order, with their comments.
Weather types with BlendWeight 0 are omitted.

Usage: python3 cfg_to_yml.py [path/to/WeatherSelectionPrototypes.cfg] [output.yml]
"""

import sys
from pathlib import Path

import yaml

from cfg_parser import Struct, load_weather_selections

REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_CFG = REPO_ROOT / "original_config" / "v2.0.5" / "GameData" / "WeatherSelectionPrototypes.cfg"
DEFAULT_OUTPUT = REPO_ROOT / "src" / "config" / "vanilla.yml"

# Weather types to include in output
WEATHER_TYPES = ["Clearly", "Cloudy", "Fogy", "Stormy", "LightRainy", "Rainy"]

# Parameters to include in output (in order)
PARAMETERS = [
    "BlendWeight",
    "WeatherDurationMin",
    "WeatherDurationMax",
    "MaximumRepeatAmount",
    "MaximumCooldownWeatherAmount",
]

# SID -> comment, in rough order on the map
REGIONS = {
    "LesserZoneWeather": "Lesser Zone",
    "GarbageWeather": "Garbage",
    "Region_WildIsland": "Wild Island",
    "KordonWeatherSelection": "Cordon",
    "BackwaterWeatherSelection": "Zaton",
    "SwampWeatherSelection": "Swamps",
    "Region_ChemicalPlant": "Chemical Plant",
    "RostokWeatherSelection": "Rostok",
    "BurnForestRegionWeather": "Burnt Forest",
    "DugaRegionWeather": "Duga",
    "MalahitWeatherSelection": "Malachite",
    "YantarWeatherSelection": "Yantar",
    "RedForestWeatherSelectionMain": "Red Forest",
    "RedForestWeatherSelectionSide": "Red Forest",
    "YanovWeatherSelection": "Yaniv",
    "JupiterWeatherSelection": "Jupiter",
    "Region_Prypiat": "Prypiat",
    "CementPlantWeatherSelection": "Cement Factory",
    "GradirniWeatherSelection": "Cooling Towers",
    "Gradirni_FireBreath_WeatherSelection": "The Fire Whirl in the North Cooling Tower",
    "Empty": "Default weather?",
    "SQ10_NoEmission_Weather": "The Wild Island side quest Shift Change",
    "Region_PromZone": '"Promzona" (Industrial Zone), a sub-area of the Chemical Plant region',
    "VortexWeatherSelection": "The Tornado in western Yaniv",
}


def region_to_dict(region: Struct) -> dict:
    """Convert a resolved weather selection into {weather: {param: value}}, skipping zero weights."""
    weathers = {}
    for weather_name in WEATHER_TYPES:
        weather = region.structs().get(weather_name)
        if weather is None or not weather.items.get("BlendWeight"):
            continue
        params = {p: weather.items[p] for p in PARAMETERS if p in weather.items}
        if params.get("MaximumCooldownWeatherAmount") == 0:
            del params["MaximumCooldownWeatherAmount"]
        weathers[weather_name] = params
    return weathers


def generate_yml(cfg_path: Path) -> str:
    """Generate vanilla.yml content from the game's WeatherSelectionPrototypes.cfg."""
    regions = load_weather_selections(cfg_path)
    parts = [f"# Generated by cfg_to_yml.py from {cfg_path.parent.parent.name}/{cfg_path.parent.name}/{cfg_path.name}\n"]
    for sid, comment in REGIONS.items():
        body = yaml.dump({sid: region_to_dict(regions[sid])}, default_flow_style=False, sort_keys=False)
        parts.append(f"# {comment}\n{body}")
    return "\n".join(parts)


def main():
    cfg_path = Path(sys.argv[1]) if len(sys.argv) >= 2 else DEFAULT_CFG
    output_path = Path(sys.argv[2]) if len(sys.argv) >= 3 else DEFAULT_OUTPUT

    if not cfg_path.is_file():
        print(f"Error: {cfg_path} not found. See README for where to get the original game config.")
        sys.exit(1)

    output_path.write_text(generate_yml(cfg_path))
    print(f"Written to {output_path}")


if __name__ == "__main__":
    main()
