name: Test

on:
  push:
    branches: [main]
  pull_request:

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-python@v7
        with:
          python-version: "3.14"

      - name: Install dependencies
        run: pip install pyyaml

      - name: Run unit tests
        run: ./tests/test.sh unit

      - name: Test generating config patch
        run: python3 src/main.py sunnier.yml
